apiVersion: 2019-12-01
location: westeurope
name: myphpapp
properties:
  imageRegistryCredentials:
    - server: $changeme.azurecr.io
      username: $changeme (this the registry name)
      password: $changeme
  containers:
    - name: php
      properties:
        image: $changeme.azurecr.io/php:v1
        resources:
          requests:
            cpu: 1
            memoryInGb: 1.5
        ports:
          - port: 80
          - port: 8080
        environmentVariables:
          - name: DB_SERVER
            value: "127.0.0.1"
          - name: DB_USERNAME
            value: "projectmaster"
          - name: DB_PASS
            value: "master1234"
          - name: DB_NAME
            value: "project"
    - name: mysqldb
      properties:
        image: $changeme.azurecr.io/mysql:v1
        resources:
          requests:
            cpu: 1
            memoryInGb: 1.5
        ports:
          - port: 3306
        environmentVariables:
          - name: MYSQL_DATABASE
            value: "project"
          - name: MYSQL_USER
            value: "projectmaster"
          - name: MYSQL_PASSWORD
            value: "master1234"
          - name: MYSQL_ROOT_PASSWORD
            value: "master1234"
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: tcp
        port: 80

tags: { exampleTag: tutorial }
type: Microsoft.ContainerInstance/containerGroups
